version: '3.8'

services:
  # Patroli BOT
  patroli-bot:
    image: patroli-bot:1.0.0
    container_name: patroli-bot
    volumes:
      - ./patroli-bot:/opt/patroli-bot
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8013:8283
    restart: always
    networks:
      - chenwoo

networks:
  chenwoo:
