version: '3.8'

services:
  # Patroli BOT
  patroli-bot:
    image: patroli-bot:1.0.0
    container_name: patroli-bot
    volumes:
      - .:/opt/patroli-bot
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8013:8283
    restart: always
    networks:
      - my_bridge_network

networks:
  my_bridge_network:
    driver: bridge
