version: '3.8'

services:
  # Patroli BOT
  patroli-bot:
    image: beauty-bot:1.0.0
    container_name: beauty-bot
    volumes:
      - ./beauty-bot:/opt/beauty-bot
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8013:8283
    restart: always
    networks:
      - chenwoo

networks:
  chenwoo:
